include:
  # - board: corneish_zen_v2_left
  # - board: corneish_zen_v2_right
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
